import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-primary-container': '#c4d2ff',
        'background': 'var(--color-background)',
        'secondary-fixed-dim': '#b1c6ff',
        'surface-container': 'var(--color-surface-container)',
        'error': 'var(--color-loss-text)',
        'tertiary-container': '#595b5b',
        'tertiary-fixed-dim': '#c6c6c7',
        'inverse-on-surface': '#f0f1f3',
        'secondary-container': 'var(--color-secondary-container)',
        'surface-dim': 'var(--color-surface-dim, #d9dadc)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'primary-fixed': '#dae2ff',
        'on-secondary-fixed': '#001946',
        'error-container': '#ffdad6',
        'surface-container-low': 'var(--color-surface-container-low)',
        'on-secondary-fixed-variant': '#00419d',
        'on-primary-fixed-variant': '#0040a2',
        'surface-bright': 'var(--color-surface)',
        'outline-variant': 'var(--color-outline-variant)',
        'inverse-primary': '#b2c5ff',
        'primary-container': 'var(--color-primary-container)',
        'on-tertiary-fixed': '#1a1c1c',
        'surface-tint': '#0c56d0',
        'surface': 'var(--color-surface)',
        'on-primary': 'var(--color-on-primary)',
        'secondary': 'var(--color-secondary)',
        'secondary-fixed': '#d9e2ff',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'inverse-surface': '#2e3132',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#b2c5ff',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'on-surface': 'var(--color-on-surface)',
        'tertiary-fixed': '#e2e2e2',
        'primary': 'var(--color-primary)',
        'on-secondary-container': '#003179',
        'on-tertiary-fixed-variant': '#454747',
        'on-secondary': '#ffffff',
        'on-background': 'var(--color-on-surface)',
        'surface-variant': 'var(--color-surface-container-highest)',
        'on-tertiary-container': '#d2d3d3',
        'on-primary-fixed': '#001848',
        'outline': 'var(--color-outline)',
        'tertiary': '#424444',
        'gain': 'var(--color-gain)',
        'gain-text': 'var(--color-gain-text)',
        'loss': 'var(--color-loss)',
        'loss-text': 'var(--color-loss-text)',
        'warning': 'var(--color-warning)',
        'warning-text': 'var(--color-warning-text)'
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'md': '0.5rem',
        'lg': '0.75rem',
        'xl': '1rem',
        '2xl': '1.5rem',
        'full': '9999px'
      },
      fontFamily: {
        'display-financial': ['var(--font-hanken)', 'system-ui', 'sans-serif'],
        'headline-lg': ['var(--font-hanken)', 'system-ui', 'sans-serif'],
        'headline-md': ['var(--font-hanken)', 'system-ui', 'sans-serif'],
        'body-lg': ['var(--font-hanken)', 'system-ui', 'sans-serif'],
        'body-md': ['var(--font-hanken)', 'system-ui', 'sans-serif'],
        'label-bold': ['var(--font-hanken)', 'system-ui', 'sans-serif'],
        'label-sm': ['var(--font-hanken)', 'system-ui', 'sans-serif']
      }
    },
  },
  plugins: [],
};

export default config;
